version: '3'
services: 
  db:
    container_name: libreriaBD
    image: mariadb:latest
    environment:
      MARIADB_USER: libreria
      MARIADB_PASSWORD: pswlibreria
      MARIADB_DATABASE: libreriaBD
      MARIADB_ROOT_PASSWORD: pswlibreria
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - "6000:3306"